name: Build and Unit Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out parser_generator
        uses: actions/checkout@v2
        with:
          path: parser_generator
          submodules: recursive
      - name: Initialize and Build
        working-directory: parser_generator
        run: |
          cargo build
      - name: Run lr_table unit tests
        working-directory: parser_generator/lr_table
        run: |
          cargo test
      - name: Run unit tests
        working-directory: parser_generator
        run: |
          cargo test
      - name: Clippy lint lr_table
        working-directory: parser_generator/lr_table
        run: |
          cargo clippy -- -D warnings
      - name: Clippy lint
        working-directory: parser_generator
        run: |
          cargo clippy -- -D warnings
