name: Build and Unit Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Check out parser_generator
        uses: actions/checkout@v2
        with:
          path: parser_generator
          submodules: recursive
      - name: Configure nightly compiler
        working-directory: parser_generator
        run: |
          rustup override set nightly
      - name: Initialize and Build
        working-directory: parser_generator
        run: |
          cargo build
      - name: Run lr_table unit tests
        working-directory: lr_table
        run: |
          cargo test
      - name: Run unit tests
        working-directory: parser_generator
        run: |
          cargo test